### ISSUE TITLE
make an ebuild out of this?

### ISSUE THREAD

**Issue by dagbdagb** [sormy/gentoo-vbox-builder#3]
I was looking for prebuilt gentoo VMs. Found none, but stumbled across this utility instead.
If you want contributors or more users, why not create an ebuild out of this?

Name it app-emulation/virtualbox-gentoo-vbox-builder   , and boom: people will find it without even trying.

Thank you for a great utility. Trying for the first time it right now. I love that it has useful defaults for everything.

**Comment by sormy** [comment]
ebuild doesn't make sense if host is windows or macOS. Probably not ebuild but prebuilt image. I'm not sure If I want to pay for traffic for relatively heavy images. AWS S3 out is $0.09 per GB in us-east-1, ~1000 downloads per month, ~2GB per download -> `1000*2*$0.09=$180` per month. If you have a hosting with free or relatively cheap bandwidth then we can cooperate and make it live :-)

**Comment by sormy** [comment]
Resolving as there is no action for this issue at this time
